#!/bin/bash -l
#SBATCH --time=8:00:00
#SBATCH --ntasks=8
#SBATCH --mem=10g
#SBATCH --tmp=10g
#SBATCH --mail-type=ALL
#SBATCH --mail-user=narim007@umn.edu
cd /home/biol3004/narim007
module load qiime2/2018.11
qiime diversity core-metrics-phylogenetic --i-phylogeny 97_otus.qza --i-table HMP.qza --p-sampling-depth 3000 --m-metadata-file HMP_mapping_file.txt --output-dir HMP3000_core-metrics-results
